spring.application.name=user-service

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/microscore_user
spring.datasource.username=root
spring.datasource.password=

spring.cloud.discovery.enabled=true
server.port=8085

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

app.jwt.secret=c2VjdXJlLXNlY3JldC1rZXktZm9yLW1pY3Jvc2NvcmUtand0LWF1dGgta2V5LTIwMjY=
app.jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true